/**
 * Optical store seed data — 8 optical/eyewear retail locations.
 * @param {import('knex').Knex} knex
 */
exports.seed = async function (knex) {
  await knex('stores').del();

  await knex('stores').insert([
    {
      store_name: 'OptiSight Vision Center - Dallas',
      region: 'Texas',
      address: '4500 McKinney Ave',
      city: 'Dallas',
      state: 'TX',
      store_type: 'hybrid',
      lat: 32.8012,
      lng: -96.7969,
      phone: '214-555-0101',
      is_active: true,
    },
    {
      store_name: 'Plano Eye Gallery',
      region: 'Texas',
      address: '8200 Preston Rd',
      city: 'Plano',
      state: 'TX',
      store_type: 'retail',
      lat: 33.0198,
      lng: -96.6989,
      phone: '972-555-0102',
      is_active: true,
    },
    {
      store_name: 'Houston Optical Hub',
      region: 'Texas',
      address: '1200 Westheimer Rd',
      city: 'Houston',
      state: 'TX',
      store_type: 'hybrid',
      lat: 29.7421,
      lng: -95.4959,
      phone: '713-555-0103',
      is_active: true,
    },
    {
      store_name: 'Phoenix LensCraft',
      region: 'Southwest',
      address: '3400 E Camelback Rd',
      city: 'Phoenix',
      state: 'AZ',
      store_type: 'retail',
      lat: 33.5094,
      lng: -111.9693,
      phone: '602-555-0104',
      is_active: true,
    },
    {
      store_name: 'Austin Vision Lab',
      region: 'Texas',
      address: '600 Congress Ave',
      city: 'Austin',
      state: 'TX',
      store_type: 'clinic',
      lat: 30.2672,
      lng: -97.7431,
      phone: '512-555-0105',
      is_active: true,
    },
    {
      store_name: 'San Antonio EyeCare',
      region: 'Texas',
      address: '100 E Houston St',
      city: 'San Antonio',
      state: 'TX',
      store_type: 'hybrid',
      lat: 29.4241,
      lng: -98.4936,
      phone: '210-555-0106',
      is_active: true,
    },
    {
      store_name: 'Scottsdale Optical Boutique',
      region: 'Southwest',
      address: '7000 E Shea Blvd',
      city: 'Scottsdale',
      state: 'AZ',
      store_type: 'retail',
      lat: 33.5810,
      lng: -111.9260,
      phone: '480-555-0107',
      is_active: true,
    },
    {
      store_name: 'Fort Worth Eye Center',
      region: 'Texas',
      address: '301 Commerce St',
      city: 'Fort Worth',
      state: 'TX',
      store_type: 'clinic',
      lat: 32.7555,
      lng: -97.3308,
      phone: '817-555-0108',
      is_active: true,
    },
  ]);
};
