/**
 * Optical product seed data — 30 products across 5 types:
 *   Frames (10), Lenses (8), Coatings (5), Contact Lenses (4), Accessories (3)
 * @param {import('knex').Knex} knex
 */
exports.seed = async function (knex) {
  await knex('products').del();

  await knex('products').insert([
    // ── Frames (10) ────────────────────────────────────────
    {
      product_name: 'Ray-Ban Aviator Classic',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Ray-Ban',
      sku: 'FRM-RB-AVI-001',
      price: 189.99,
      inventory_count: 85,
      attributes: JSON.stringify({
        frame_material: 'metal',
        frame_shape: 'aviator',
        gender: 'unisex',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Oakley Half Jacket 2.0',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Oakley',
      sku: 'FRM-OAK-HJ2-002',
      price: 159.99,
      inventory_count: 62,
      attributes: JSON.stringify({
        frame_material: 'plastic',
        frame_shape: 'rectangular',
        gender: 'male',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Prada Linea Rossa',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Prada',
      sku: 'FRM-PRA-LRS-003',
      price: 279.99,
      inventory_count: 35,
      attributes: JSON.stringify({
        frame_material: 'acetate',
        frame_shape: 'rectangular',
        gender: 'unisex',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Tom Ford FT5401',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Tom Ford',
      sku: 'FRM-TF-5401-004',
      price: 329.99,
      inventory_count: 22,
      attributes: JSON.stringify({
        frame_material: 'acetate',
        frame_shape: 'round',
        gender: 'unisex',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Coach HC6065',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Coach',
      sku: 'FRM-COA-6065-005',
      price: 169.99,
      inventory_count: 48,
      attributes: JSON.stringify({
        frame_material: 'acetate',
        frame_shape: 'cat_eye',
        gender: 'female',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Nike 7090',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Nike',
      sku: 'FRM-NIK-7090-006',
      price: 129.99,
      inventory_count: 95,
      attributes: JSON.stringify({
        frame_material: 'plastic',
        frame_shape: 'rectangular',
        gender: 'male',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Warby Parker Durand',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Warby Parker',
      sku: 'FRM-WP-DUR-007',
      price: 95.00,
      inventory_count: 120,
      attributes: JSON.stringify({
        frame_material: 'acetate',
        frame_shape: 'round',
        gender: 'unisex',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Burberry BE2150',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Burberry',
      sku: 'FRM-BUR-2150-008',
      price: 219.99,
      inventory_count: 30,
      attributes: JSON.stringify({
        frame_material: 'acetate',
        frame_shape: 'rectangular',
        gender: 'female',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Gucci GG0010O',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Gucci',
      sku: 'FRM-GUC-0010-009',
      price: 349.99,
      inventory_count: 18,
      attributes: JSON.stringify({
        frame_material: 'metal',
        frame_shape: 'round',
        gender: 'unisex',
        prescription_compatible: true,
      }),
    },
    {
      product_name: 'Flexon E1110',
      category: 'Eyewear',
      product_type: 'frame',
      brand: 'Flexon',
      sku: 'FRM-FLX-1110-010',
      price: 149.99,
      inventory_count: 55,
      attributes: JSON.stringify({
        frame_material: 'titanium',
        frame_shape: 'rectangular',
        gender: 'male',
        prescription_compatible: true,
      }),
    },

    // ── Lenses (8) ─────────────────────────────────────────
    {
      product_name: 'Single Vision Standard',
      category: 'Lenses',
      product_type: 'lens',
      brand: 'Essilor',
      sku: 'LNS-SV-STD-001',
      price: 89.99,
      inventory_count: 300,
      attributes: JSON.stringify({
        lens_type: 'single_vision',
        material: 'CR-39',
        index: 1.50,
      }),
    },
    {
      product_name: 'Progressive Premium',
      category: 'Lenses',
      product_type: 'lens',
      brand: 'Essilor',
      sku: 'LNS-PRG-PRM-002',
      price: 299.99,
      inventory_count: 150,
      attributes: JSON.stringify({
        lens_type: 'progressive',
        material: 'high_index',
        index: 1.67,
      }),
    },
    {
      product_name: 'Bifocal Standard',
      category: 'Lenses',
      product_type: 'lens',
      brand: 'Zeiss',
      sku: 'LNS-BIF-STD-003',
      price: 149.99,
      inventory_count: 200,
      attributes: JSON.stringify({
        lens_type: 'bifocal',
        material: 'CR-39',
        index: 1.50,
      }),
    },
    {
      product_name: 'High-Index 1.67',
      category: 'Lenses',
      product_type: 'lens',
      brand: 'Essilor',
      sku: 'LNS-HI-167-004',
      price: 199.99,
      inventory_count: 120,
      attributes: JSON.stringify({
        lens_type: 'single_vision',
        material: 'high_index',
        index: 1.67,
      }),
    },
    {
      product_name: 'Polycarbonate',
      category: 'Lenses',
      product_type: 'lens',
      brand: 'Hoya',
      sku: 'LNS-PC-STD-005',
      price: 129.99,
      inventory_count: 250,
      attributes: JSON.stringify({
        lens_type: 'single_vision',
        material: 'polycarbonate',
        index: 1.59,
      }),
    },
    {
      product_name: 'Trivex',
      category: 'Lenses',
      product_type: 'lens',
      brand: 'Hoya',
      sku: 'LNS-TRV-STD-006',
      price: 159.99,
      inventory_count: 180,
      attributes: JSON.stringify({
        lens_type: 'single_vision',
        material: 'trivex',
        index: 1.53,
      }),
    },
    {
      product_name: 'Digital Progressive',
      category: 'Lenses',
      product_type: 'lens',
      brand: 'Zeiss',
      sku: 'LNS-DPG-PRM-007',
      price: 349.99,
      inventory_count: 80,
      attributes: JSON.stringify({
        lens_type: 'progressive',
        material: 'high_index',
        index: 1.74,
      }),
    },
    {
      product_name: 'Photochromic Transitions',
      category: 'Lenses',
      product_type: 'lens',
      brand: 'Transitions',
      sku: 'LNS-PHT-TRN-008',
      price: 249.99,
      inventory_count: 140,
      attributes: JSON.stringify({
        lens_type: 'single_vision',
        material: 'polycarbonate',
        index: 1.59,
        photochromic: true,
      }),
    },

    // ── Coatings (5) ───────────────────────────────────────
    {
      product_name: 'Anti-Glare Premium',
      category: 'Coatings',
      product_type: 'coating',
      brand: 'Crizal',
      sku: 'CTG-AG-PRM-001',
      price: 79.99,
      inventory_count: 500,
      attributes: JSON.stringify({
        coating_type: 'anti_reflective',
        compatible_lens_types: ['single_vision', 'progressive', 'bifocal'],
      }),
    },
    {
      product_name: 'Blue Light Filter',
      category: 'Coatings',
      product_type: 'coating',
      brand: 'Crizal',
      sku: 'CTG-BLF-STD-002',
      price: 59.99,
      inventory_count: 450,
      attributes: JSON.stringify({
        coating_type: 'blue_light',
        compatible_lens_types: ['single_vision', 'progressive', 'bifocal'],
      }),
    },
    {
      product_name: 'Scratch Resistant',
      category: 'Coatings',
      product_type: 'coating',
      brand: 'Essilor',
      sku: 'CTG-SCR-STD-003',
      price: 39.99,
      inventory_count: 600,
      attributes: JSON.stringify({
        coating_type: 'scratch_resistant',
        compatible_lens_types: ['single_vision', 'progressive', 'bifocal'],
      }),
    },
    {
      product_name: 'UV Protection',
      category: 'Coatings',
      product_type: 'coating',
      brand: 'Essilor',
      sku: 'CTG-UV-STD-004',
      price: 29.99,
      inventory_count: 700,
      attributes: JSON.stringify({
        coating_type: 'uv_protection',
        compatible_lens_types: ['single_vision', 'progressive', 'bifocal'],
      }),
    },
    {
      product_name: 'Hydrophobic Coating',
      category: 'Coatings',
      product_type: 'coating',
      brand: 'Zeiss',
      sku: 'CTG-HYD-STD-005',
      price: 49.99,
      inventory_count: 400,
      attributes: JSON.stringify({
        coating_type: 'hydrophobic',
        compatible_lens_types: ['single_vision', 'progressive', 'bifocal'],
      }),
    },

    // ── Contact Lenses (4) ─────────────────────────────────
    {
      product_name: 'Acuvue Oasys Daily',
      category: 'Contact Lenses',
      product_type: 'contact_lens',
      brand: 'Acuvue',
      sku: 'CL-ACV-OAS-001',
      price: 45.99,
      inventory_count: 200,
      attributes: JSON.stringify({
        wear_type: 'daily',
        toric: false,
        multifocal: false,
        pack_size: 30,
      }),
    },
    {
      product_name: 'Air Optix Night & Day',
      category: 'Contact Lenses',
      product_type: 'contact_lens',
      brand: 'Alcon',
      sku: 'CL-ALN-AND-002',
      price: 59.99,
      inventory_count: 150,
      attributes: JSON.stringify({
        wear_type: 'monthly',
        toric: false,
        multifocal: false,
        pack_size: 6,
      }),
    },
    {
      product_name: 'Dailies Total 1',
      category: 'Contact Lenses',
      product_type: 'contact_lens',
      brand: 'Alcon',
      sku: 'CL-ALN-DT1-003',
      price: 52.99,
      inventory_count: 180,
      attributes: JSON.stringify({
        wear_type: 'daily',
        toric: false,
        multifocal: false,
        pack_size: 30,
      }),
    },
    {
      product_name: 'Biofinity Toric',
      category: 'Contact Lenses',
      product_type: 'contact_lens',
      brand: 'CooperVision',
      sku: 'CL-CV-BFT-004',
      price: 49.99,
      inventory_count: 130,
      attributes: JSON.stringify({
        wear_type: 'monthly',
        toric: true,
        multifocal: false,
        pack_size: 6,
      }),
    },

    // ── Accessories (3) ────────────────────────────────────
    {
      product_name: 'Oakley Hard Case',
      category: 'Accessories',
      product_type: 'accessory',
      brand: 'Oakley',
      sku: 'ACC-OAK-HC-001',
      price: 29.99,
      inventory_count: 250,
      attributes: JSON.stringify({
        accessory_type: 'case',
        fits: 'all_standard_frames',
      }),
    },
    {
      product_name: 'Microfiber Cleaning Kit',
      category: 'Accessories',
      product_type: 'accessory',
      brand: 'OptiSight',
      sku: 'ACC-OS-MCK-002',
      price: 12.99,
      inventory_count: 500,
      attributes: JSON.stringify({
        accessory_type: 'cleaning_kit',
        includes: ['microfiber_cloth', 'spray_bottle', 'pouch'],
      }),
    },
    {
      product_name: 'Lens Cleaning Solution',
      category: 'Accessories',
      product_type: 'accessory',
      brand: 'OptiSight',
      sku: 'ACC-OS-LCS-003',
      price: 8.99,
      inventory_count: 800,
      attributes: JSON.stringify({
        accessory_type: 'cleaning_solution',
        volume_oz: 4,
      }),
    },
  ]);
};
